### ISSUE TITLE
Update binary for Windows

### ISSUE THREAD

**Issue by sergeevabc** [nicjansma/rename-regex#12]
Dear Nic,
your [article][1] about RR links to version [1.0][2], whereas changelog indicates 1.5 is the current one.
Could you be so kind to update Windows binary for the rest of us who are mere users without a compiler?

[1]: https://nicj.net/windows-command-line-regular-expression-renaming-tool-renameregex/
[2]: https://github.com/nicjansma/rename-regex/downloads

**Comment by nicjansma** [comment]
Hi @sergeevabc!  Yeah unfortunately Github deprecated the _Downloads_ are so I can't update it anymore.

The latest binaries should always be in the `bin/` folder: https://github.com/nicjansma/rename-regex/tree/master/bin

I've just updated it for 1.6: https://github.com/nicjansma/rename-regex/blob/master/bin/RR.exe

**Comment by diev** [comment]
Hi @nicjansma! Your product is great! But please do not waste the *sources* Git system with *binaries*. Every binary version (and not properly working also!) is saved entirely and forever inside and takes its space in the repository. Every developer will load that with `git`.

Update your link to the latest binaries as <https://github.com/nicjansma/rename-regex/releases/latest> and upload your binaries there. Or configure an automation for build-and-deploy on <https://www.appveyor.com/> as for Windows tools.

Also some firewalls block passing of `exe` through. For Windows it will be better to package into `zip`, imho.

**Comment by diev** [comment]
I have done a sample release in my account to illustrate the GitHub current way to deploy binaries. The permanent link is as <https://github.com/diev/rename-regex/releases/latest>.

Another way to publish binaries could be performed by a customized web page (sources in `/docs` folder) for a repository as <https://dievdo.ru/WhoCan/> looks for example. There is an automatic list of last *Downloads* thrown by the template <https://github.com/diev/WhoCan/blob/master/docs/_includes/download.html>.

**Comment by diev** [comment]
> Could you be so kind to update Windows binary for the rest of us who are mere users without a compiler?

@sergeevabc if you have c# sources for Windows, you have few compilers in your Windows also! :)

    %windir%\Microsoft.NET\Framework\v3.5\csc.exe
    %windir%\Microsoft.NET\Framework\v4.0.30319\csc.exe

I think you can read the Russian language here - [https://github.com/diev/Verba-OW-Automation](https://github.com/diev/Verba-OW-Automation#%D1%87%D1%82%D0%BE-%D0%BD%D0%B5-%D1%82%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82%D1%81%D1%8F).

**Comment by sergeevabc** [comment]
Dear @diev, do you have a compiled binary of RR with the issues you [solved](https://github.com/nicjansma/rename-regex/pull/21)? For unknown reason, @nicjansma hesitates to integrate your patches, or even to reply about a [recursion bug](https://github.com/nicjansma/rename-regex/issues/17). I rename folders quite often and a reliable Windows command line utility to do that is in high demand. By the way, have a look at [Brename](https://github.com/shenwei356/brename).
