### ISSUE TITLE
Old links - did you notice ? 

### ISSUE THREAD

**Issue by steinhaug** [nicjansma/rename-regex#15]
I believe you forgot to update this page:
https://github.com/nicjansma/rename-regex/downloads

I just downloaded and installed your v1.0.0.0 version, making me look for a way of renaming directories and now I see you are indeed updated since v1.0.0.0 :)

**Comment by nicjansma** [comment]
Yeah unfortunately Github doesn't let us update those pages anymore.  I'll fix the links from my original article!
