### ISSUE TITLE
/r recursive does not work

### ISSUE THREAD

**Issue by steinhaug** [nicjansma/rename-regex#16]
I downloaded the latest v1.5 .exe.

I cannot get the recursive command to work. I tried renaming from within folder, works fine. Going level up, needing the /r does not work.

Any way I could debug this ?

Error is: "Could not rename..."

**Comment by nicjansma** [comment]
Hey @steinhaug!

Looks like this is something I broke in 1.5.0.

Should be fixed in the latest released 1.6.1!

* https://github.com/nicjansma/rename-regex/releases/tag/v1.6.1
* https://github.com/nicjansma/rename-regex/blob/v1.6.1/bin/RR.exe
