### ISSUE TITLE
Update the build

### ISSUE THREAD

**Issue by tbertels** [nicjansma/rename-regex#5]
The code has changed since the 30 Jan 2012 build (commands added), so ApplicationVersion could be updated in https://github.com/nicjansma/rename-regex/blob/master/source/RenameRegex.csproj and a new build could be published for this great tool.

**Comment by nicjansma** [comment]
@tbertels just published the `RR.exe` and release for `1.4.0`:

https://github.com/nicjansma/rename-regex/releases/tag/v1.4.0

Note the application version isn't taken from `<ApplicationVersion>` in `RenameRegex.csproj`, it's from https://github.com/nicjansma/rename-regex/blob/master/source/Properties/AssemblyInfo.cs#L38
