### ISSUE TITLE
Like #3, recursion is not working

### ISSUE THREAD

**Issue by Earl-Brown** [nicjansma/rename-regex#6]
In #3 the comments say "I get an exception when I use 'rr /r ..." - I also get an exception (second path fragment must not be a drive or UNC name).  If I use "rr ... /r" I don't get an exception, but rr does nothing.

**Comment by nicjansma** [comment]
@Earl-Brown I'm not able to reproduce, can you share the exact command line you're using?

What version are you using?

**Comment by nicjansma** [comment]
Please re-open if you have this issue still!
